language: ruby
rvm:
- 2.5.0
cache: bundler
sudo: false
notifications:
  slack:
    secure: ctW1nMBHHPhVmiccD4yOTsif5adWpge+HwAK1ZfGFJbS+xQlldTox7JGlvVx+TTxpUgUej+nH4g7OdPVBP39iQtJE3UGg/rqDJRO5W4tqiklBCZaYp5wP0GZkd2BlFfeb4/ymzszW5MjnyZehZKejcejRNcr+kjs1vTnshFjJkZPRSTcFkmjXEWcNEnF9uy1rYvSBnE5pNkvQzBU9lMw/jVpM4DXBDFh8h397fP2GlRPFX8RekzyYFUxadHo0lj+TWKMG2uwCaAaa0xjvRV4hoN5YzgLcAJK6TON4FA9ZKFxb2ptKb0wmNKVJqVNGmO8GROR7zSsTbA5DKsi/VKm+IK6QYsJB0CgoRWv54p6XrPbapEP6OCKeigYpe9dYBRQ/ZMqg8Wd/m2BkSVh9NGhJr6p8aAudrxSFUMCMTkGfEQFYGWzG99iyGA4J7w4oqzVgRFArRRVKPWIJHQfOceELcUnsxoQAaHjnTm9sB+9MPmmCymKVtU6u8Qpv1OMOFvWTP3ouCh2gbHJV8WuQE4NpBn36odBgpwrdOO6DUncPJjLFgdmsDeH3+G01Evz2Kg/qbqxUaHl3JNMY2anDFOvOUzvu5mEjifKGkDPxnbhJ4os8xXrKXeNCFYJU42w+cSn4V6JwpOoWZnofcXThBfosd6Y9URvwelJkWfULy6Urm4=
